#starter配置
mystarter:
  config:
    enable: true
    student:
      id: 1
      name: zhangsan
    klass:
      students:
        - id: 2
          name: lisi
        - id: 3
          name: wangwu

# mybatis配置数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: 123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: mybatis.entity
