spring:
  datasource:
    master:
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3307/shop?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password:
    slave:
      - driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3308/shop?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password:
      - driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3309/shop?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password:
    #负载均衡策略
    loadBalance: ROUND_ROBIN

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: mybatis.entity

