server:
  port: 8087
  servlet:
    context-path: /
  address: 0.0.0.0
spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/hmily_order?useUnicode=true&characterEncoding=utf8
        username: root
        password:
mybatis:
  type-aliases-package: hmily.dubbo.order.entity
  config-location: classpath:mybatis/mybatis-config.xml